### ISSUE TITLE
Halide 2.1: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by shipingli** [halide/Halide#2872]
I was trying to build blur example in Halide2.1, after running  test-Blur-app-android, I see below error:

+ /home/lishiping/VCP/ARM64_Toolchain/bin/aarch64-linux-android-c++ -std=c++11 -fopenmp -I /home/lishiping/VCP/Qualcomm/HALIDE_Tools/2.1/Halide/include -I /home/lishiping/VCP/Qualcomm/HALIDE_Tools/2.1/Halide/support -I ./bin/arm-64-android -Wall -O3 test.cpp bin/arm-64-android/halide_blur.a -o bin/arm-64-android/test -llog -fPIE -pie

Traceback (most recent call last):
  File "/home/lishiping/VCP/ARM64_Toolchain/bin/aarch64-linux-android-c++", line 67, in <module>
    main(sys.argv)
  File "/home/lishiping/VCP/ARM64_Toolchain/bin/aarch64-linux-android-c++", line 64, in main
    cw.invoke_compiler()
  File "/home/lishiping/VCP/ARM64_Toolchain/bin/aarch64-linux-android-c++", line 59, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory

I checked the code, and see 

    os.execv(self.argv0, self.execargs)

 where self.argv0 is /home/lishiping/VCP/ARM64_Toolchain/bin/real-aarch64-linux-android-c++'. 

What is it doing here and why it put "real-" to the compiler? And how to fix it ? 

Thanks

**Comment by shipingli** [comment]
Fixed by using the Android NDK comes with Hexagon SDK.
