### ISSUE TITLE
Halide profiler stopped working

### ISSUE THREAD

**Issue by nikoki** [halide/Halide#2972]
I am currently using this halide commit:

_commit e7c50c8689a91f0a49e46bb32a3f5fc29ac3c686 (HEAD -> master, origin/master, origin/HEAD)
Merge: 5307e4036 9dd363c55
Author: Steven Johnson <srj@google.com>
Date:   Wed May 9 19:23:07 2018 -0700
    Merge pull request #2948 from halide/srj-asan
    Fix JIT-only ASAN crash_

And halide profiler is not working anymore.
When I try to use command, while runing my pipeline:
adb logcat | grep halide
I see complete pipeline time in overhead stage instead divided between stages.
It worked before, and when i roll back to this commit I used before:
_commit fe85f6a70e9d2f16d5a1591b90c8e598dbcf4c7f
Merge: 46d8e9e 0409941
Author: Steven Johnson <srj@google.com>
Date:   Thu Feb 15 09:40:42 2018 -0800
    Merge pull request #2751 from halide/srj-tsel
    Add tuple_select() to python bindings._

everything works fine.
Thanks,
Ivan

**Comment by steven-johnson** [comment]
Can you please provide a more complete set of steps-to-repeat, so I can investigate? (ie, what build targets, build commands, system, OS, etc are you using)

**Comment by nikoki** [comment]
Hi Steven,
Sorry for the lack of info.
I am using Ubuntu 18.04 and i am trying to develop some algorithms for Qualcomm Hexagon.
We are using LLVM 5.0 and Clang 5.0.

When we try to execute our code natively on hexagon and run profiler (by adding target=arm-64-android-hvx_128-profile) in the meantime we get output as described above - all time is being calculated in overhead stage instead of time being divided between user pipeline stages.
Let me know if you need some specific outputs.
Thanks,
Ivan

**Comment by steven-johnson** [comment]
I still don't have enough information to investigate. 
- What is the specific Pipeline you are running? (Please include build and run commands)
- If the pipeline you are using isn't public, can you replicate it with something in Halide (e.g., one of the apps/)?
- Does this only happen when running on Hexagon? 
- The commit you reference above is a change that should have absolutely no effect unless you are building with ASAN enabled. Are you?
- The comment above seems to indicate that you've bisected a particular injection point (commit) for the bug, but it's not clear to me what that point is. Can you clarify?

**Comment by nikoki** [comment]
Adding Ugi for more information and answers to given questions.
Thanks,
Ivan

**Comment by nikoki** [comment]
Just to add some clarification:
 - We did not bisect a bug to the special commit, we just tried the newest
commit once we had one of our dev-boxes reinstalled and found out that we
have a problem. To confirm that this is Halide problem, we rolled back to
one of the previous versions we were using before on other dev-box, where
we know it worked. Those commits are the ones given above and we did not
try any of the other commits that are in between.
- We are not using ASAN
- Problem reproduces on both Hexagon and Host, but all we care about is
Hexagon, and that is the only platform that we are developing and testing
for.

Thanks,
Ivan

**Comment by pranavb-ca** [comment]
Can you try explicitly adding "halide_profiler_report(nullptr)" at the end of your application on the ARM side?

**Comment by steven-johnson** [comment]
Thanks for the extra info. I hope to investigate soon, but am still underwater with other issues.

**Comment by steven-johnson** [comment]
I've tried using the example you included on host (x86-64-osx in my case) but it don't see any issue with overhead. I'll have to set up a system for running on a Hexagon device to try to debug. If you can confirm whether or not this issue is Hexagon-specific (vs generic to all build targets) it would help me immensely.

**Comment by steven-johnson** [comment]
probably-dumb-q: I’m trying to use the Android NDK make-standalone-toolchain tool for the first time ever on my Linux box (since your example requires its)... and the tools it produces just plain don't work. e.g., aarch64-linux-android-c++ is a python wrapper that just fails immediately with "path not found”. 

Are there known gotchas with this tool? Am I holding it wrong?

(This is from downloading NDK r17 from https://developer.android.com/ndk/downloads/ and doing 
```
$ export ANDROID_ARM64_TOOLCHAIN=/Users/srj/ANDROID_ARM64_TOOLCHAIN
$ $ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch arm64 --api 21 --install-dir  /Users/srj/ANDROID_ARM64_TOOLCHAIN
$ /Users/srj/ANDROID_ARM64_TOOLCHAIN/bin/aarch64-linux-android-c++
Traceback (most recent call last):
  File "/Users/srj/ANDROID_ARM64_TOOLCHAIN/bin/aarch64-linux-android-c++", line 66, in <module>
    main(sys.argv)
  File "/Users/srj/ANDROID_ARM64_TOOLCHAIN/bin/aarch64-linux-android-c++", line 63, in main
    cw.invoke_compiler()
  File "/Users/srj/ANDROID_ARM64_TOOLCHAIN/bin/aarch64-linux-android-c++", line 58, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 2] No such file or directory
```

**Comment by ugigugi** [comment]
To answer your first comment... it looks here on my machine that it's hexagon-specific problem :/ When running the example using `make run-host` things look fine (profile output make sense in a way that the total execution time is not totally observed as the _overhead_ time).

Regarding your second comment... I can see that you are trying to build it directly as an android NDK. I was going through the Hexagon SDK, download it (take the latest one, I think it's 3.3.3) and install it. After that, you will need to export some variables. For building a toolchain you will need something like:
`export SDK_LOC=/<path-to-Qualcomm-Hexagon-SDK>/Hexagon_SDK/3.3.3`
`export ANDROID_NDK_HOME=$SDK_LOC/tools/android-ndk-r14b`
`export ANDROID_ARM64_TOOLCHAIN=$ANDROID_NDK_HOME/platforms/android-21/arch-arm64`

finally, run something like:
`$ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh --arch=arm64 --platform=android-21 --install-dir=$ANDROID_ARM64_TOOLCHAIN --force`

Now it should work... It still might happen that when you try to compile one of your own apps, some very basic .h files will not be found. My hack was to copy `/usr` folder that was there initially (inside `platforms/android-21/arch-arm64` folder) from android-22 version into `android-21/arch-arm64/sysroot` and that should solve the problem (this is where it would look for those .h files, but since `usr` folder does not exist in `sysroot` after building your own toolchain, you need to copy it manually).

Hope this will help you somehow...

Ugi

**Comment by steven-johnson** [comment]
Hi, just an update: I haven't forgotten about this, just continue to have other things jump ahead of it in line. Sorry about that.

**Comment by Fenglele** [comment]
Hi Steven,

I came to the same issue, the overhead is always more than > 97% even for a simple operation such as averaging the bursts of images. My setup is LLVM 6.0 and Clang 6.0, Ubuntu 16.04, Qualcomm 845. Is there any update?

Thanks, 
Feng

**Comment by pranavb-ca** [comment]
While working on something else, i ran into this problem myself recently. I might have a fix for this in a few days because I am working on a different more urgent issue right now.

**Comment by Fenglele** [comment]
Thank you, Pranav. Plz keep updated if available.

**Comment by pranavb-ca** [comment]
https://github.com/halide/Halide/pull/3304 tries to fix the problem where the sampling thread sees the HVX reporting work done as overhead because the HVX side wasn't getting the correct "current_func".

**Comment by pranavb-ca** [comment]
@Fenglele - You should try https://github.com/halide/Halide/pull/3304

**Comment by abadams** [comment]
> [!NOTE]
> **Automated triage:** this issue was flagged by Claude as likely safe to close, for the
> reason below. The reasoning was checked against the current source, and a second pass
> tried and failed to refute it, but no human verified this specific text.
> **If the reason is wrong, please reopen the issue and say so** — some fraction of these
> are expected to be wrong.

**Reason (CLOSE_FIXED):** The reporter confirmed the problem was Hexagon-specific: all time was attributed to "overhead" because the sampling thread could not see the current func while work ran on HVX. PR #3304 fixed exactly that by plumbing the remote profiler's current func back to the host, and it was merged; the mechanism is still in the current runtime.

**Evidence:** PR #3304 merged 2018-10-02 as commit 5569b3ac2 "Fix profiling when a stage is offloaded to HVX" (ancestor of HEAD); src/runtime/hexagon_host.cpp:37-38, 92-98, 200-201, 480-491 (remote_profiler_set_current_func / get_remote_profiler_state)

Closing: fixed by #3304 (merged as 5569b3ac2), which propagates the HVX-side current func to the host profiler so offloaded stages are no longer all attributed to "overhead" — see src/runtime/hexagon_host.cpp:480-491. Please reopen with a current repro if you still see this.
