### ISSUE TITLE
Issue with GPU and python binding on apps/bilateral_grid.py

### ISSUE THREAD

**Issue by cheng-chi** [halide/Halide#3082]
Hi! I have just downloaded Halide and trying to verify it works. With the Halide and python binding both build against LLVM-6.0 without error, and majority of CPU examples working, when I tried to test GPU by setting environment variables:
```
export HL_TARGET=cuda
export HL_JIT_TARGET=cuda
```
`python3 bilateral_grid.py` returned following error:
```
Compiling for GPU.
Traceback (most recent call last):
  File "bilateral_grid.py", line 162, in <module>
    main()
  File "bilateral_grid.py", line 148, in main
    bilateral_grid = get_bilateral_grid(input, r_sigma, s_sigma)
  File "bilateral_grid.py", line 69, in get_bilateral_grid
    histogram.compute_root().reorder(c, z, x, y).gpu_tile(x, y, 8, 8);
TypeError: gpu_tile(): incompatible function arguments. The following argument types are supported:
    1. (self: halide.Func, x: halide.VarOrRVar, bx: halide.VarOrRVar, tx: halide.VarOrRVar, x_size: halide.Expr, tail: halide.TailStrategy=TailStrategy.Auto, device_api: halide.DeviceAPI=DeviceAPI.Default_GPU) -> halide.Func
    2. (self: halide.Func, x: halide.VarOrRVar, tx: halide.VarOrRVar, x_size: halide.Expr, tail: halide.TailStrategy=TailStrategy.Auto, device_api: halide.DeviceAPI=DeviceAPI.Default_GPU) -> halide.Func
    3. (self: halide.Func, x: halide.VarOrRVar, y: halide.VarOrRVar, bx: halide.VarOrRVar, by: halide.VarOrRVar, tx: halide.VarOrRVar, ty: halide.VarOrRVar, x_size: halide.Expr, y_size: halide.Expr, tail: halide.TailStrategy=TailStrategy.Auto, device_api: halide.DeviceAPI=DeviceAPI.Default_GPU) -> halide.Func
    4. (self: halide.Func, x: halide.VarOrRVar, y: halide.VarOrRVar, tx: halide.VarOrRVar, ty: halide.VarOrRVar, x_size: halide.Expr, y_size: halide.Expr, tail: halide.TailStrategy=TailStrategy.Auto, device_api: halide.DeviceAPI=DeviceAPI.Default_GPU) -> halide.Func
    5. (self: halide.Func, x: halide.VarOrRVar, y: halide.VarOrRVar, z: halide.VarOrRVar, bx: halide.VarOrRVar, by: halide.VarOrRVar, bz: halide.VarOrRVar, tx: halide.VarOrRVar, ty: halide.VarOrRVar, tz: halide.VarOrRVar, x_size: halide.Expr, y_size: halide.Expr, z_size: halide.Expr, tail: halide.TailStrategy=TailStrategy.Auto, device_api: halide.DeviceAPI=DeviceAPI.Default_GPU) -> halide.Func
    6. (self: halide.Func, x: halide.VarOrRVar, y: halide.VarOrRVar, z: halide.VarOrRVar, tx: halide.VarOrRVar, ty: halide.VarOrRVar, tz: halide.VarOrRVar, x_size: halide.Expr, y_size: halide.Expr, z_size: halide.Expr, tail: halide.TailStrategy=TailStrategy.Auto, device_api: halide.DeviceAPI=DeviceAPI.Default_GPU) -> halide.Func

Invoked with: <halide.Func 'histogram'>, <halide.Var 'x'>, <halide.Var 'y'>, 8, 8
```

Dose this means my halide is installed incorrectly, or the example itself has some issue?
Thanks!

**Comment by abadams** [comment]
Looks like the example uses a deprecated interface that we eventually cut. Try changing gpu_tile(x, y, 8, 8) to gpu_tile(x, y, xi, yi, 8, 8), where xi and yi are two new Vars.

**Comment by Infinoid** [comment]
PR #4805 fixed the use of deprecated `gpu_tile()` arguments, I think this issue can be closed.
