### ISSUE TITLE
JIT is crashing under LLVM7 on arm32

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3411]
We reliably crash inside ExecutionEngine::getFunctionAddress() when running with LLVM7 on arm32-linux; I haven't seen this on other CPU+LLVM combinations yet; ~any of the many tests we have that use JIT will reliably reproduce it.

**Comment by steven-johnson** [comment]
From bisection, the injection point is in https://reviews.llvm.org/rL325700 (from waaaay back in Feb 21 2018)

**Comment by steven-johnson** [comment]
Update: the bisection point is likely a red herring; while it unambiguously transitions from success to failure at that point on the system I was using for testing, it's utterly unrelated to ARM code generation or execution; further, making even trivial edits (e.g. adding `exit(1)` to the new code paths) to the changes in rL325700 can cause it to once again start working.

Current guess is that there is some code-size limit being exceeded that is causing the heartache, and this just happens to be the change that inflicts it; exactly what and how is still not clear.

**Comment by steven-johnson** [comment]
I tried a different arm32 system on which gdb is able to run without barfing, and made some progress; at least one of the JIT tests (image_io) segfaults with this traceback:

```
#0  0xf34fce48 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#1  0xf4b7b452 in std::_Rb_tree_iterator<std::pair<llvm::RelocationValueRef const, unsigned int> > std::_Rb_tree<llvm::RelocationValueRef, std::pair<llvm::RelocationValueRef const, unsigned int>, std::_Select1st<std::pair<llvm::RelocationValueRef const, unsigned int> >, std::less<llvm::RelocationValueRef>, std::allocator<std::pair<llvm::RelocationValueRef const, unsigned int> > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<llvm::RelocationValueRef const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<llvm::RelocationValueRef const, unsigned int> >, std::piecewise_construct_t const&, std::tuple<llvm::RelocationValueRef const&>&&, std::tuple<>&&) ()
   from halide-build/bin/libHalide.so
#2  0xf4b81776 in std::map<llvm::RelocationValueRef, unsigned int, std::less<llvm::RelocationValueRef>, std::allocator<std::pair<llvm::RelocationValueRef const, unsigned int> > >::operator[](llvm::RelocationValueRef const&) ()
   from halide-build/bin/libHalide.so
#3  0xf4b82b32 in llvm::RuntimeDyldELF::processRelocationRef(unsigned int, llvm::object::content_iterator<llvm::object::RelocationRef>, llvm::object::ObjectFile const&, std::map<llvm::object::SectionRef, unsigned int, std::less<llvm::object::SectionRef>, std::allocator<std::pair<llvm::object::SectionRef const, unsigned int> > >&, std::map<llvm::RelocationValueRef, unsigned int, std::less<llvm::RelocationValueRef>, std::allocator<std::pair<llvm::RelocationValueRef const, unsigned int> > >&) ()
   from halide-build/bin/libHalide.so
#4  0xf4b70b04 in llvm::RuntimeDyldImpl::loadObjectImpl(llvm::object::ObjectFile const&) ()
   from halide-build/bin/libHalide.so
#5  0xf4b84b08 in llvm::RuntimeDyldELF::loadObject(llvm::object::ObjectFile const&) ()
   from halide-build/bin/libHalide.so
#6  0xf4b6bfe8 in llvm::RuntimeDyld::loadObject(llvm::object::ObjectFile const&) ()
---Type <return> to continue, or q <return> to quit---
   from halide-build/bin/libHalide.so
#7  0xf4b5d236 in llvm::MCJIT::generateCodeForModule(llvm::Module*) ()
   from halide-build/bin/libHalide.so
#8  0xf4b5c368 in llvm::MCJIT::findSymbol(std::string const&, bool) ()
   from halide-build/bin/libHalide.so
#9  0xf4b5c61e in llvm::MCJIT::getSymbolAddress(std::string const&, bool) ()
   from halide-build/bin/libHalide.so
#10 0xf4b5c85a in llvm::MCJIT::getFunctionAddress(std::string const&) ()
   from halide-build/bin/libHalide.so
#11 0xf3d20a56 in Halide::Internal::(anonymous namespace)::compile_and_get_function(llvm::ExecutionEngine&, std::string const&) [clone .constprop.311] () from halide-build/bin/libHalide.so
#12 0xf3d23e24 in Halide::Internal::JITModule::compile_module(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >, std::string const&, Halide::Target const&, std::vector<Halide::Internal::JITModule, std::allocator<Halide::Internal::JITModule> > const&, std::vector<std::string, std::allocator<std::string> > const&) () from halide-build/bin/libHalide.so
#13 0xf3d253b2 in Halide::Internal::(anonymous namespace)::make_module(llvm::Module*, Halide::Target, Halide::Internal::(anonymous namespace)::RuntimeKind, std::vector<Halide::Internal::JITModule, std::allocator<Halide::Internal::JITModule> > const&, bool) ()
   from halide-build/bin/libHalide.so
#14 0xf3d25be8 in Halide::Internal::JITSharedRuntime::get(llvm::Module*, Halide::Target const&, bool) ()
   from halide-build/bin/libHalide.so
#15 0xf3d2640a in Halide::Internal::JITModule::JITModule(Halide::Module const&, Halide::Internal::LoweredFunc const&, std::vector<Halide::Internal::J---Type <return> to continue, or q <return> to quit---
ITModule, std::allocator<Halide::Internal::JITModule> > const&) ()
   from halide-build/bin/libHalide.so
#16 0xf3d7fdd8 in Halide::Pipeline::compile_jit(Halide::Target const&) ()
   from halide-build/bin/libHalide.so
#17 0xf3d80816 in Halide::Pipeline::realize(Halide::Pipeline::RealizationArg, Halide::Target const&, Halide::ParamMap const&) ()
   from halide-build/bin/libHalide.so
#18 0xf3d8112a in Halide::Pipeline::realize(std::vector<int, std::allocator<int> >, Halide::Target const&, Halide::ParamMap const&) ()
   from halide-build/bin/libHalide.so
#19 0xf3c5b860 in Halide::Func::realize(std::vector<int, std::allocator<int> >, Halide::Target const&, Halide::ParamMap const&) ()
   from halide-build/bin/libHalide.so
#20 0xf3c5b95e in Halide::Func::realize(int, int, int, Halide::Target const&, Halide::ParamMap const&) ()
   from halide-build/bin/libHalide.so
#21 0x00171394 in do_test<unsigned char> ()
    at halide/test/correctness/image_io.cpp:169
#22 0x0016a91a in main (argc=1, argv=0xfffefb24)
    at halide/test/correctness/image_io.cpp:228
```

**Comment by steven-johnson** [comment]
This turned out to be a bug in gcc 5.5 on arm systems.
