### ISSUE TITLE
HelloPytorch example with gpu - INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by saulzar** [halide/Halide#5078]
I get this error for test_gpu_single and test_gpu_double trying to run the example:
pytorch-1.5, cuda-10.2

Needed to add the flag std=c++14 in setup.py to compile.
```

ERROR: test_gpu_single (__main__.TestAdd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 27, in test_gpu_single
    self._test_add(is_cuda=True, is_double=False)
  File "test.py", line 69, in _test_add
    res = th.autograd.gradcheck(add, [self.a, self.b], eps=1e-2)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 281, in gradcheck
    analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(tupled_inputs, o, nondet_tol=nondet_tol)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 157, in get_analytical_jacobian
    retain_graph=True, allow_unused=True)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 158, in grad
    inputs, allow_unused)
RuntimeError: !_grad_loss_output_wrt_input_a_buffer.host_dirty() INTERNAL ASSERT FAILED at /tmp/pip-req-build-brck_00n/bin/host/add_halidegrad_cuda_float32.pytorch.h:88, please report a bug to PyTorch. device not synchronized for buffer _grad_loss_output_wrt_input_a, make sure all update stages are excplicitly computed on GPU.

```

**Comment by saulzar** [comment]
The assertion comes from this line in the generated wrapper:

`    AT_ASSERTM(!_grad_loss_output_wrt_input_a_buffer.host_dirty(),"device not synchronized for buffer _grad_loss_output_wrt_input_a, make sure all update stages are excplicitly computed on GPU.");`

**Comment by abadams** [comment]
> [!NOTE]
> **Automated triage:** this issue was flagged by Claude as likely safe to close, for the reason below. The reasoning was checked against the current source, and a second pass tried and failed to refute it, but no human verified this specific text. **If the reason is wrong, please reopen the issue and say so** — some fraction of these are expected to be wrong.

**Reason (CLOSE_FIXED):** The failing symbol `add_halidegrad_cuda_float32` is the auto-differentiated op, which at the time was built with `auto_schedule=true` but no autoscheduler plugin loaded, so the gradient stages were not scheduled on the GPU and the output buffer came back host-dirty. #6234 added the GPU-capable Li2018 autoscheduler to exactly those targets.

**Evidence:** Commit `95198a7bb` (#6234, "Remove torch/extension dependency and fix PyTorch example, adding the correct (GPU) autoscheduler") adds `-p libautoschedule_li2018.so -s Li2018` to the `add_halidegrad_cuda_float32`/`float64` rules in `apps/HelloPyTorch/Makefile`; the CMake build carries the same setting at `apps/HelloPyTorch/CMakeLists.txt:176-193` (`AUTOSCHEDULER Halide::Li2018` with `${cuda_features}`).

Closing: the reported failure was in `add_halidegrad_cuda_*`, which was built with `auto_schedule=true` but no autoscheduler, leaving the gradient stages on the host. #6234 (commit `95198a7bb`) reworked the example to use the GPU-capable Li2018 autoscheduler for those ops (`apps/HelloPyTorch/CMakeLists.txt:176-193`). Please reopen with a repro against current `apps/HelloPyTorch` if it still fires.
