### ISSUE TITLE
auto_schedule with python_bindings

### ISSUE THREAD

**Issue by lukastruemper** [halide/Halide#6791]
Hello,

I started using the Halide python_bindings and tested whether it supports the auto_schedulers. I tried to wrap the blur.py example into a pipeline and call auto_schedule with Adams2019:

```
pipeline = hl.Pipeline(blur)
pipeline.auto_schedule("Adams2019", hl.get_target_from_environment())
```

This results in an error that "Adams2019" is not found and there are no known autoscheduler

```
Traceback (most recent call last):
  File "/home/lukas/Documents/repos/Halide/python_bindings/apps/blur.py", line 81, in <module>
    main()
  File "/home/lukas/Documents/repos/Halide/python_bindings/apps/blur.py", line 62, in main
    pipeline.auto_schedule("Adams2019", hl.get_target_from_environment())
RuntimeError: Error: Unknown autoscheduler name 'Adams2019'; known names are:

```

Is there a technical problem with how the auto-schedulers work (construct the features from the python interface?) or is it just a problem of correctly building the bindings?

Would be cool if we could get this to work. I am trying to understand the performance of Halide on [NPBench](https://github.com/spcl/npbench) and compare it with pythonic DSLs like numpy and DaCe.

Cheers,
Lukas

**Comment by lukastruemper** [comment]
Cool, this worked. Thanks!
