### ISSUE TITLE
Many python tests fail when building halide on i386: `JIT session error: Symbols not found: [ __udivdi3 ]`

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#7679]
https://buildd.debian.org/status/fetch.php?pkg=halide&arch=i386&ver=16.0.0-2&stamp=1689162571&raw=0
```
The following tests FAILED:
	651 - python_correctness_atomics (Failed)
	652 - python_correctness_autodiff (Failed)
	653 - python_correctness_basics (Failed)
	655 - python_correctness_boundary_conditions (Failed)
	657 - python_correctness_callable (Failed)
	659 - python_correctness_division (Failed)
	661 - python_correctness_float_precision_test (Failed)
	662 - python_correctness_iroperator (Failed)
	664 - python_correctness_multipass_constraints (Failed)
	665 - python_correctness_pystub (Failed)
	666 - python_correctness_rdom (Failed)
	667 - python_correctness_realize_warnings (Failed)
	669 - python_correctness_tuple_select (Failed)
	674 - python_tutorial_lesson_01_basics (Failed)
	675 - python_tutorial_lesson_02_input_image (Failed)
	676 - python_tutorial_lesson_03_debugging_1 (Failed)
	677 - python_tutorial_lesson_04_debugging_2 (Failed)
	678 - python_tutorial_lesson_05_scheduling_1 (Failed)
	679 - python_tutorial_lesson_06_realizing_over_shifted_domains (Failed)
	680 - python_tutorial_lesson_07_multi_stage_pipelines (Failed)
	681 - python_tutorial_lesson_08_scheduling_2 (Failed)
	682 - python_tutorial_lesson_09_update_definitions (Failed)
	686 - python_tutorial_lesson_12_using_the_gpu (Failed)
	687 - python_tutorial_lesson_13_tuples (Failed)
```

```
        Start 651: python_correctness_atomics
538/591 Test #651: python_correctness_atomics .................................***Failed    0.90 sec
JIT session error: Symbols not found: [ __udivdi3 ]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python_bindings/test/correctness/atomics.py", line 24, in <module>
    test_atomics()
  File "/<<PKGBUILDDIR>>/python_bindings/test/correctness/atomics.py", line 13, in test_atomics
    b = f.realize([5])
        ^^^^^^^^^^^^^^
halide.halide_.HalideError: Internal Error at /<<PKGBUILDDIR>>/src/JITModule.cpp:226 triggered by user code at : Condition failed: addr: Failed to materialize symbols: { (main, { halide_malloc, halide_float16_bits_to_double, halide_error_bounds_inference_call_failed, halide_set_custom_free, halide_default_error, halide_free, halide_float16_bits_to_float, halide_error, halide_error_explicit_bounds_too_small, halide_error_bad_type, halide_cache_cleanup, halide_print, halide_error_extern_stage_failed, halide_trace_cleanup, halide_set_error_handler, halide_error_access_out_of_bounds, halide_default_print, halide_error_buffer_allocation_too_large, halide_set_custom_print, halide_default_semaphore_try_acquire, _ZN6Halide7Runtime8Internal27default_desired_num_threadsEv, halide_error_bad_dimensions, _ZN6Halide7Runtime8Internal27enqueue_work_already_lockedEiPNS1_4workES3_, halide_error_buffer_extents_too_large, _ZN6Halide7Runtime8Internal15Synchronization25broadcast_parking_control16requeue_callbackERKNS2_15validate_actionEbb, halide_host_cpu_count, halide_error_buffer_extents_negative, _ZN6Halide7Runtime8Internal17custom_do_par_forE, _ZN6Halide7Runtime8Internal15Synchronization15parking_control12before_sleepEv, _ZN6Halide7Runtime8Internal16buffer_has_shapeEPK15halide_buffer_tPK18halide_dimension_t, _ZN6Halide7Runtime8Internal15Synchronization15parking_control4parkEj, _ZN6Halide7Runtime8Internal15Synchronization21mutex_parking_control6unparkEib, _ZN6Halide7Runtime8Internal19custom_do_loop_taskE, halide_default_buffer_copy, _ZN6Halide7Runtime8Internal15Synchronization9word_lock11unlock_fullEv, halide_buffer_copy_already_locked, halide_device_and_host_free_as_destructor, _ZN6Halide7Runtime8Internal21custom_semaphore_initE, halide_device_host_nop_free, _ZN6Halide7Runtime8Internal15Synchronization9word_lock9lock_fullEv, halide_default_device_crop, halide_profiler_shutdown, halide_default_device_slice, _ZN6Halide7Runtime8Internal19spawn_thread_helperEPv, halide_default_do_parallel_tasks, halide_buffer_copy, halide_default_device_release_crop, halide_device_release_crop, halide_internal_aligned_alloc, halide_set_custom_get_library_symbol, halide_spawn_thread, halide_device_crop, _ZN6Halide7Runtime8Internal13worker_threadEPv, halide_device_slice, halide_error_bad_extern_fold, _ZN6Halide7Runtime8Internal15Synchronization16lock_bucket_pairEjj, halide_device_free, halide_error_bad_fold, halide_device_and_host_malloc, halide_error_host_is_null, halide_device_and_host_free, halide_device_malloc, _ZN6Halide7Runtime8Internal21allocation_pools_lockE, halide_device_free_as_destructor, _ZN6Halide7Runtime8Internal15Synchronization15parking_control14unpark_requeueEjjj, halide_copy_to_device, _ZN6Halide7Runtime8Internal36halide_reuse_device_allocations_flagE, halide_device_sync, halide_jit_module_adjust_ref_count, halide_error_requirement_failed, halide_jit_module_argument, halide_error_fold_factor_too_small, halide_default_device_wrap_native, _ZN6Halide7Runtime8Internal17device_copy_mutexE, halide_default_device_detach_native, halide_device_detach_native, halide_thread_pool_cleanup, halide_error_no_device_interface, halide_default_device_and_host_malloc, halide_error_specialize_fail, halide_default_device_and_host_free, halide_device_wrap_native, $.shared runtime.__inits.0, halide_error_storage_bound_too_small, _ZN6Halide7Runtime8Internal24custom_semaphore_releaseE, halide_get_symbol, halide_error_param_too_small_i64, _ZN6Halide7Runtime8Internal15Synchronization11lock_bucketEj, _ZN6Halide7Runtime8Internal15Synchronization15parking_control10unpark_oneEj, halide_load_library, halide_error_buffer_is_null, _ZN6Halide7Runtime8Internal28custom_semaphore_try_acquireE, halide_error_buffer_argument_is_null, halide_get_library_symbol, halide_error_host_and_device_dirty, halide_error_constraint_violated, halide_mutex_unlock, halide_mutex_array_lock, halide_default_get_library_symbol, halide_profiler_report_unlocked, halide_error_param_too_large_i64, _ZTVN6Halide7Runtime8Internal15Synchronization25broadcast_parking_controlE, halide_default_do_loop_task, halide_profiler_get_state, halide_mutex_array_unlock, halide_error_param_too_large_u64, halide_set_custom_load_library, halide_error_param_too_small_f64, _ZN6Halide7Runtime8Internal25custom_get_library_symbolE, halide_error_device_crop_failed, halide_error_param_too_small_u64, _ZN6Halide7Runtime8Internal15Synchronization22signal_parking_control6unparkEib, _ZN6Halide7Runtime8Internal23find_or_create_pipelineEPKciPKy, halide_error_out_of_memory, halide_device_release, halide_default_do_par_for, halide_default_do_task, _ZN6Halide7Runtime8Internal24sampling_profiler_threadEPv, halide_mutex_array_create, halide_error_param_too_large_f64, halide_mutex_array_destroy, halide_profiler_reset_unlocked, copy_to_device_already_locked, halide_join_thread, halide_copy_to_host, halide_msan_annotate_memory_is_initialized, halide_error_device_dirty_with_no_device_support, halide_set_gpu_device, halide_set_custom_get_symbol, halide_profiler_sample, halide_error_device_interface_no_device, halide_error_unaligned_host_ptr, halide_register_device_allocation_pool, halide_cond_signal, _ZN6Halide7Runtime8Internal18copy_memory_helperERKNS1_11device_copyEixx, _ZN6Halide7Runtime8Internal27copy_to_host_already_lockedEPvP15halide_buffer_t, halide_mutex_lock, _ZN6Halide7Runtime8Internal9bill_funcEP21halide_profiler_stateiyi, _ZN6Halide7Runtime8Internal15Synchronization15parking_control8validateERNS2_15validate_actionE, halide_set_custom_do_task, halide_default_semaphore_init, _ZN6Halide7Runtime8Internal19halide_trace_bufferE, halide_profiler_memory_allocate, halide_set_num_threads, _ZN6Halide7Runtime8Internal17halide_trace_fileE, halide_profiler_memory_free, _ZTVN6Halide7Runtime8Internal15Synchronization21mutex_parking_controlE, halide_error_debug_to_file_failed, halide_profiler_report, _ZN6Halide7Runtime8Internal22halide_trace_file_lockE, halide_thread_yield, halide_set_custom_parallel_runtime, _ZN6Halide7Runtime8Internal22halide_gpu_device_lockE, halide_profiler_get_pipeline_state, halide_set_custom_do_par_for, halide_shutdown_thread_pool, _ZN6Halide7Runtime8Internal28worker_thread_already_lockedEPNS1_4workE, halide_profiler_pipeline_start, halide_default_semaphore_release, _ZN6Halide7Runtime8Internal29halide_gpu_device_initializedE, halide_profiler_stack_peak_update, _ZN6Halide7Runtime8Internal24make_host_to_device_copyEPK15halide_buffer_t, _ZN6Halide7Runtime8Internal17custom_get_symbolE, _ZN6Halide7Runtime8Internal8djb_hashEPKhj, halide_set_custom_do_loop_task, halide_semaphore_init, _ZN6Halide7Runtime8Internal19custom_load_libraryE, _ZN6Halide7Runtime8Internal11prune_cacheEv, halide_do_parallel_tasks, _ZN6Halide7Runtime8Internal16make_buffer_copyEPK15halide_buffer_tbS4_b, halide_do_par_for, halide_memoization_cache_set_size, _ZN6Halide7Runtime8Internal17halide_gpu_deviceE, _ZN6Halide7Runtime8Internal10keys_equalEPKhS3_j, _ZTVN6Halide7Runtime8Internal15Synchronization22signal_parking_controlE, halide_profiler_reset, halide_default_get_symbol, halide_default_load_library, _ZN6Halide7Runtime8Internal24make_device_to_host_copyEPK15halide_buffer_t, _ZTVN6Halide7Runtime8Internal15Synchronization20wait_parking_controlE, _ZN6Halide7Runtime8Internal10CacheEntry4initEPKhjjPK15halide_buffer_tiPPS5_by, halide_semaphore_try_acquire, halide_semaphore_release, halide_memoization_cache_evict, _ZN6Halide7Runtime8Internal10CacheEntry7destroyEv, _ZN6Halide7Runtime8Internal16memoization_lockE, halide_default_free, halide_string_to_string, halide_memoization_cache_cleanup, halide_uint64_to_string, _ZN6Halide7Runtime8Internal11copy_memoryERKNS1_11device_copyEPv, _ZN6Halide7Runtime8Internal31pixel_type_to_matlab_class_codeE, halide_memoization_cache_lookup, halide_error_constraints_make_required_region_smaller, halide_set_custom_malloc, halide_memoization_cache_store, halide_memoization_cache_release, _ZN6Halide7Runtime8Internal30pixel_type_to_matlab_type_codeE, _ZN6Halide7Runtime8Internal21get_pointer_to_headerEPh, _ZN6Halide7Runtime8Internal35halide_trace_file_internally_openedE, halide_trace, halide_type_to_string, halide_default_malloc, halide_set_custom_trace, halide_buffer_to_string, halide_internal_malloc_alignment, _ZN6Halide7Runtime8Internal19halide_custom_traceE, _ZN6Halide7Runtime8Internal30pixel_type_to_tiff_sample_typeE, halide_shutdown_trace, halide_int64_to_string, halide_debug_to_file, _ZN6Halide7Runtime8Internal29halide_trace_file_initializedE, _ZN6Halide7Runtime8Internal9ends_withEPKcS3_, halide_double_to_string, _ZN6Halide7Runtime8Internal12header_bytesEv, halide_trace_helper, halide_pointer_to_string, halide_internal_aligned_free, _ZN6Halide7Runtime8Internal23device_allocation_poolsE, _ZN6Halide7Runtime8Internal24custom_do_parallel_tasksE, halide_get_gpu_device, _ZN6Halide7Runtime8Internal33halide_unused_force_include_typesEv, halide_reuse_device_allocations, _ZN6Halide7Runtime8Internal13error_handlerE, halide_fopen, __orc_deinit_func.shared runtime, _ZN6Halide7Runtime8Internal11custom_freeE, halide_set_trace_file, halide_default_trace, _ZN6Halide7Runtime8Internal12custom_printE, halide_get_trace_file, halide_can_reuse_device_allocations, _ZN6Halide7Runtime8Internal15Synchronization21mutex_parking_control8validateERNS2_15validate_actionE, _ZN6Halide7Runtime8Internal15Synchronization18unlock_bucket_pairERNS2_11bucket_pairE, _ZN6Halide7Runtime8Internal15Synchronization15parking_control16requeue_callbackERKNS2_15validate_actionEbb, halide_reference_clock_inited, _ZN6Halide7Runtime8Internal18current_cache_sizeE, _ZN6Halide7Runtime8Internal10work_queueE, halide_reference_clock, _ZN6Halide7Runtime8Internal19least_recently_usedE, _ZN6Halide7Runtime8Internal18most_recently_usedE, _ZN6Halide7Runtime8Internal15Synchronization5tableE, _ZN6Halide7Runtime8Internal14max_cache_sizeE, _ZN6Halide7Runtime8Internal14custom_do_taskE, _ZN6Halide7Runtime8Internal13cache_entriesE, _ZN6Halide7Runtime8Internal15Synchronization20wait_parking_control6unparkEib, _ZN6Halide7Runtime8Internal15Synchronization20wait_parking_control12before_sleepEv, _ZN6Halide7Runtime8Internal15Synchronization15parking_control6unparkEib, halide_current_time_ns, halide_profiler_pipeline_end, halide_start_clock, halide_msan_check_memory_is_initialized, halide_do_task, halide_cond_wait, _ZN6Halide7Runtime8Internal15Synchronization25broadcast_parking_control8validateERNS2_15validate_actionE, halide_do_loop_task, halide_msan_check_buffer_is_initialized, _ZN6Halide7Runtime8Internal13custom_mallocE, halide_msan_annotate_buffer_is_initialized, halide_cond_broadcast, halide_sleep_ms, _ZN6Halide7Runtime8Internal15Synchronization20wait_parking_control8validateERNS2_15validate_actionE, halide_msan_annotate_buffer_is_initialized_as_destructor, halide_release_jit_module, halide_use_jit_module }) }


        Start 652: python_correctness_autodiff
539/591 Test #652: python_correctness_autodiff ................................***Failed    0.66 sec
JIT session error: Symbols not found: [ __udivdi3 ]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python_bindings/test/correctness/autodiff.py", line 68, in <module>
    test_autodiff()
  File "/<<PKGBUILDDIR>>/python_bindings/test/correctness/autodiff.py", line 23, in test_autodiff
    d_f_init_buf = d_f_init.realize([3])
                   ^^^^^^^^^^^^^^^^^^^^^
halide.halide_.HalideError: Internal Error at /<<PKGBUILDDIR>>/src/JITModule.cpp:226 triggered by user code at : Condition failed: addr: Failed to materialize symbols: { (main, { _ZN6Halide7Runtime8Internal16buffer_has_shapeEPK15halide_buffer_tPK18halide_dimension_t, halide_error_bad_type, _ZTVN6Halide7Runtime8Internal15Synchronization21mutex_parking_controlE, halide_error_bad_dimensions, halide_default_semaphore_try_acquire, halide_register_device_allocation_pool, halide_device_release, _ZN6Halide7Runtime8Internal27copy_to_host_already_lockedEPvP15halide_buffer_t, _ZN6Halide7Runtime8Internal10keys_equalEPKhS3_j, halide_error_explicit_bounds_too_small, _ZN6Halide7Runtime8Internal15Synchronization9word_lock11unlock_fullEv, halide_reuse_device_allocations, halide_error_buffer_allocation_too_large, halide_error_buffer_extents_negative, _ZTVN6Halide7Runtime8Internal15Synchronization20wait_parking_controlE, halide_fopen, _ZN6Halide7Runtime8Internal24make_device_to_host_copyEPK15halide_buffer_t, _ZN6Halide7Runtime8Internal27default_desired_num_threadsEv, halide_can_reuse_device_allocations, _ZTVN6Halide7Runtime8Internal15Synchronization22signal_parking_controlE, halide_error_access_out_of_bounds, halide_device_release_crop, _ZN6Halide7Runtime8Internal15Synchronization15parking_control4parkEj, _ZN6Halide7Runtime8Internal19custom_load_libraryE, halide_float16_bits_to_float, _ZN6Halide7Runtime8Internal15Synchronization15parking_control12before_sleepEv, halide_set_custom_malloc, _ZN6Halide7Runtime8Internal15Synchronization9word_lock9lock_fullEv, halide_device_slice, _ZN6Halide7Runtime8Internal17custom_get_symbolE, halide_buffer_to_string, halide_default_device_release_crop, _ZN6Halide7Runtime8Internal22halide_gpu_device_lockE, halide_do_loop_task, halide_int64_to_string, halide_error_bounds_inference_call_failed, halide_default_free, halide_error_extern_stage_failed, halide_pointer_to_string, _ZN6Halide7Runtime8Internal17halide_gpu_deviceE, _ZN6Halide7Runtime8Internal15Synchronization15parking_control8validateERNS2_15validate_actionE, _ZN6Halide7Runtime8Internal15Synchronization25broadcast_parking_control8validateERNS2_15validate_actionE, halide_float16_bits_to_double, halide_double_to_string, halide_memoization_cache_evict, halide_shutdown_thread_pool, halide_buffer_copy_already_locked, halide_join_thread, halide_memoization_cache_release, halide_buffer_copy, _ZN6Halide7Runtime8Internal17halide_trace_fileE, halide_default_semaphore_release, halide_device_host_nop_free, _ZN6Halide7Runtime8Internal29halide_gpu_device_initializedE, halide_uint64_to_string, halide_default_buffer_copy, _ZN6Halide7Runtime8Internal19halide_trace_bufferE, halide_string_to_string, _ZN6Halide7Runtime8Internal29halide_trace_file_initializedE, halide_default_device_slice, _ZTVN6Halide7Runtime8Internal15Synchronization25broadcast_parking_controlE, _ZN6Halide7Runtime8Internal24make_host_to_device_copyEPK15halide_buffer_t, halide_device_crop, _ZN6Halide7Runtime8Internal25custom_get_library_symbolE, halide_default_semaphore_init, halide_memoization_cache_store, _ZN6Halide7Runtime8Internal22halide_trace_file_lockE, halide_default_device_crop, halide_default_error, _ZN6Halide7Runtime8Internal19spawn_thread_helperEPv, halide_error, halide_internal_malloc_alignment, halide_device_detach_native, halide_memoization_cache_lookup, halide_set_error_handler, _ZN6Halide7Runtime8Internal19halide_custom_traceE, _ZN6Halide7Runtime8Internal28custom_semaphore_try_acquireE, halide_default_device_and_host_free, _ZN6Halide7Runtime8Internal23device_allocation_poolsE, halide_default_print, _ZN6Halide7Runtime8Internal11prune_cacheEv, _ZN6Halide7Runtime8Internal35halide_trace_file_internally_openedE, halide_device_wrap_native, halide_set_custom_print, _ZN6Halide7Runtime8Internal24custom_semaphore_releaseE, _ZN6Halide7Runtime8Internal17custom_do_par_forE, _ZN6Halide7Runtime8Internal31pixel_type_to_matlab_class_codeE, halide_device_and_host_free_as_destructor, _ZN6Halide7Runtime8Internal8djb_hashEPKhj, _ZN6Halide7Runtime8Internal30pixel_type_to_tiff_sample_typeE, _ZN6Halide7Runtime8Internal21custom_semaphore_initE, halide_default_device_wrap_native, halide_default_device_detach_native, _ZN6Halide7Runtime8Internal10CacheEntry4initEPKhjjPK15halide_buffer_tiPPS5_by, halide_type_to_string, halide_error_no_device_interface, halide_set_custom_parallel_runtime, _ZN6Halide7Runtime8Internal16memoization_lockE, halide_set_custom_do_par_for, _ZN6Halide7Runtime8Internal13cache_entriesE, halide_set_custom_do_loop_task, halide_error_specialize_fail, _ZN6Halide7Runtime8Internal14custom_do_taskE, halide_error_requirement_failed, _ZN6Halide7Runtime8Internal30pixel_type_to_matlab_type_codeE, _ZN6Halide7Runtime8Internal19custom_do_loop_taskE, halide_get_symbol, halide_reference_clock, halide_set_custom_load_library, halide_set_custom_do_task, halide_load_library, _ZN6Halide7Runtime8Internal19least_recently_usedE, halide_set_num_threads, _ZN6Halide7Runtime8Internal18most_recently_usedE, halide_memoization_cache_set_size, halide_set_custom_get_symbol, _ZN6Halide7Runtime8Internal10work_queueE, halide_mutex_array_lock, halide_error_host_and_device_dirty, halide_default_get_library_symbol, _ZN6Halide7Runtime8Internal13error_handlerE, _ZN6Halide7Runtime8Internal36halide_reuse_device_allocations_flagE, halide_profiler_report_unlocked, halide_mutex_array_destroy, halide_error_host_is_null, _ZN6Halide7Runtime8Internal15Synchronization5tableE, halide_error_device_dirty_with_no_device_support, _ZN6Halide7Runtime8Internal12custom_printE, halide_error_device_interface_no_device, halide_mutex_array_create, halide_reference_clock_inited, _ZN6Halide7Runtime8Internal18current_cache_sizeE, halide_error_unaligned_host_ptr, _ZN6Halide7Runtime8Internal14max_cache_sizeE, halide_error_fold_factor_too_small, _ZN6Halide7Runtime8Internal33halide_unused_force_include_typesEv, _ZN6Halide7Runtime8Internal15Synchronization22signal_parking_control6unparkEib, halide_profiler_get_state, _ZN6Halide7Runtime8Internal18copy_memory_helperERKNS1_11device_copyEixx, _ZN6Halide7Runtime8Internal17device_copy_mutexE, halide_error_storage_bound_too_small, halide_error_buffer_is_null, halide_error_bad_fold, halide_error_device_crop_failed, halide_set_gpu_device, _ZN6Halide7Runtime8Internal21allocation_pools_lockE, _ZN6Halide7Runtime8Internal11custom_freeE, halide_msan_annotate_memory_is_initialized, halide_error_bad_extern_fold, halide_error_param_too_large_f64, $.shared runtime.__inits.0, halide_use_jit_module, halide_profiler_sample, halide_jit_module_adjust_ref_count, halide_release_jit_module, halide_error_param_too_large_u64, halide_error_param_too_large_i64, _ZN6Halide7Runtime8Internal9bill_funcEP21halide_profiler_stateiyi, halide_error_param_too_small_f64, halide_cond_signal, halide_jit_module_argument, _ZN6Halide7Runtime8Internal24custom_do_parallel_tasksE, _ZN6Halide7Runtime8Internal15Synchronization25broadcast_parking_control16requeue_callbackERKNS2_15validate_actionEbb, halide_mutex_array_unlock, _ZN6Halide7Runtime8Internal23find_or_create_pipelineEPKciPKy, halide_error_debug_to_file_failed, _ZN6Halide7Runtime8Internal24sampling_profiler_threadEPv, halide_error_out_of_memory, halide_print, halide_msan_annotate_buffer_is_initialized_as_destructor, _ZN6Halide7Runtime8Internal15Synchronization15parking_control16requeue_callbackERKNS2_15validate_actionEbb, halide_default_load_library, halide_profiler_reset_unlocked, halide_default_get_symbol, halide_profiler_report, halide_error_buffer_argument_is_null, halide_profiler_memory_free, halide_error_buffer_extents_too_large, halide_semaphore_try_acquire, halide_profiler_memory_allocate, halide_semaphore_release, halide_get_library_symbol, halide_profiler_stack_peak_update, halide_semaphore_init, halide_profiler_pipeline_start, halide_error_param_too_small_u64, halide_do_parallel_tasks, halide_do_par_for, halide_error_param_too_small_i64, halide_profiler_get_pipeline_state, halide_error_constraint_violated, _ZN6Halide7Runtime8Internal15Synchronization15parking_control10unpark_oneEj, _ZN6Halide7Runtime8Internal13custom_mallocE, halide_error_constraints_make_required_region_smaller, _ZN6Halide7Runtime8Internal15Synchronization21mutex_parking_control6unparkEib, halide_mutex_unlock, halide_get_gpu_device, halide_default_trace, _ZN6Halide7Runtime8Internal15Synchronization11lock_bucketEj, _ZN6Halide7Runtime8Internal11copy_memoryERKNS1_11device_copyEPv, halide_get_trace_file, _ZN6Halide7Runtime8Internal10CacheEntry7destroyEv, halide_set_trace_file, halide_memoization_cache_cleanup, _ZN6Halide7Runtime8Internal21get_pointer_to_headerEPh, halide_shutdown_trace, _ZN6Halide7Runtime8Internal9ends_withEPKcS3_, halide_profiler_reset, halide_sleep_ms, halide_default_do_task, _ZN6Halide7Runtime8Internal12header_bytesEv, _ZN6Halide7Runtime8Internal15Synchronization15parking_control14unpark_requeueEjjj, halide_profiler_pipeline_end, halide_host_cpu_count, halide_current_time_ns, halide_thread_yield, halide_msan_check_memory_is_initialized, halide_debug_to_file, halide_mutex_lock, _ZN6Halide7Runtime8Internal15Synchronization20wait_parking_control6unparkEib, halide_msan_check_buffer_is_initialized, halide_cond_wait, _ZN6Halide7Runtime8Internal15Synchronization20wait_parking_control12before_sleepEv, halide_start_clock, halide_default_do_par_for, halide_trace_helper, halide_msan_annotate_buffer_is_initialized, halide_default_do_loop_task, halide_trace, __orc_deinit_func.shared runtime, halide_cond_broadcast, _ZN6Halide7Runtime8Internal15Synchronization18unlock_bucket_pairERNS2_11bucket_pairE, halide_default_do_parallel_tasks, halide_spawn_thread, _ZN6Halide7Runtime8Internal13worker_threadEPv, halide_set_custom_get_library_symbol, _ZN6Halide7Runtime8Internal15Synchronization15parking_control6unparkEib, halide_set_custom_trace, _ZN6Halide7Runtime8Internal15Synchronization16lock_bucket_pairEjj, _ZN6Halide7Runtime8Internal15Synchronization21mutex_parking_control8validateERNS2_15validate_actionE, _ZN6Halide7Runtime8Internal16make_buffer_copyEPK15halide_buffer_tbS4_b, halide_do_task, halide_profiler_shutdown, halide_internal_aligned_free, halide_internal_aligned_alloc, halide_set_custom_free, halide_malloc, halide_default_device_and_host_malloc, halide_free, halide_device_and_host_free, _ZN6Halide7Runtime8Internal28worker_thread_already_lockedEPNS1_4workE, halide_default_malloc, halide_thread_pool_cleanup, halide_trace_cleanup, halide_cache_cleanup, halide_device_and_host_malloc, _ZN6Halide7Runtime8Internal27enqueue_work_already_lockedEiPNS1_4workES3_, halide_device_free, halide_device_free_as_destructor, _ZN6Halide7Runtime8Internal15Synchronization20wait_parking_control8validateERNS2_15validate_actionE, halide_copy_to_device, halide_device_sync, halide_device_malloc, halide_copy_to_host, copy_to_device_already_locked }) }



```

**Comment by steven-johnson** [comment]
The Python bindings aren't supported (or tested) on any 32-bit target.

**Comment by LebedevRI** [comment]
Thanks
Why is this not being caught at CMake time?

**Comment by steven-johnson** [comment]
> Thanks. Why is this not being caught at CMake time?

Ah, good point. We should do so :-)
