### ISSUE TITLE
Fuse a split with PredicateStores leads to infinite simplication

### ISSUE THREAD

**Issue by TH3CHARLie** [halide/Halide#7742]
A simple repro:
```
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Var x, y, x_outer, x_inner, y_x_inner_fused;
    Func f;
    f(x, y) = x + y;
    f.split(x, x_outer, x_inner, 2, TailStrategy::PredicateStores).fuse(y, x_inner, y_x_inner_fused);
    Pipeline p(f);
    p.realize({100, 100});
    return 0;
}
```

**Comment by TH3CHARLie** [comment]
gdb output:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff08cb9ec in Halide::Internal::(anonymous namespace)::MakeSimplifications::mutate(Halide::Expr const&) ()
   from /home/xuanda/dev/Serializer/Halide-clean/build/src/libHalide.so.17
(gdb) bt
#0  0x00007ffff08cb9ec in Halide::Internal::(anonymous namespace)::MakeSimplifications::mutate(Halide::Expr const&) ()
   from /home/xuanda/dev/Serializer/Halide-clean/build/src/libHalide.so.17
#1  0x00007ffff08cb9ef in Halide::Internal::(anonymous namespace)::MakeSimplifications::mutate(Halide::Expr const&) ()
   from /home/xuanda/dev/Serializer/Halide-clean/build/src/libHalide.so.17
#2  0x00007ffff08cb9ef in Halide::Internal::(anonymous namespace)::MakeSimplifications::mutate(Halide::Expr const&) ()
   from /home/xuanda/dev/Serializer/Halide-clean/build/src/libHalide.so.17
#3  0x00007ffff08cb9ef in Halide::Internal::(anonymous namespace)::MakeSimplifications::mutate(Halide::Expr const&) ()
   from /home/xuanda/dev/Serializer/Halide-clean/build/src/libHalide.so.17
```
