### ISSUE TITLE
How to compile and use with pytorch as extension?

### ISSUE THREAD

**Issue by StrongChris** [halide/Halide#7797]
Hello, I am looking to use Halide with Pytorch. I haven't been able to figure out how to compile the extension correctly. Below is a reproducible example and logs of the error I am getting.

```cpp
#include <torch/extension.h>
#include "Halide.h"

bool is_available() {
    return true;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("is_available", &is_available, "is_available");
}
```

```python
from setuptools import setup
from torch.utils.cpp_extension import CppExtension, BuildExtension

extra_objects = ["/home/chris/haltorch/Halide/lib/libHalide.a"]
compile_args = ["-std=c++17", "-L/home/chris/haltorch/Halide/lib", "-lHalide", "-lpthread", "-ldl"]

setup(
    name="haltorch",
    verbose=True,
    ext_modules=[
        CppExtension("haltorch", ["hal.cpp"], extra_objects=extra_objects, extra_compile_args=compile_args)
    ],
    include_dirs=["/home/chris/haltorch/Halide/include"],
    cmdclass={"build_ext": BuildExtension},
)
```

I also tried with the jit loader

```python
import torch
from torch.utils.cpp_extension import load

hal = load(name="hal", sources=["hal.cpp"], verbose=True, build_directory='build', extra_include_paths=["/home/chris/haltorch/Halide/include"], extra_ldflags=["-L/home/chris/haltorch/Halide/lib", "-lHalide", "-lpthread", "-ldl"])

assert hal.is_available()
print("done")
```

```
(.venv) chris@sc12:~/haltorch$ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import haltorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libc10.so: cannot open shared object file: No such file or directory
>>> import torch
>>> import haltorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/chris/haltorch/haltorch.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6Halide8Internal13Introspection19get_source_locationEv
```

What do I need to do to make this work?

**Comment by abadams** [comment]
> [!NOTE]
> **Automated triage:** this issue was flagged by Claude as likely safe to close, for the reason below. The reasoning was checked against the current source, and a second pass tried and failed to refute it, but no human verified this specific text. **If the reason is wrong, please reopen the issue and say so** — some fraction of these are expected to be wrong.

**Reason (CLOSE_STALE):** This is a usage question, not a defect: the reporter linked `libHalide` (the compiler) into a torch extension. The specific undefined symbol they hit, `Halide::Internal::Introspection::get_source_location`, no longer exists anywhere in the tree, and the supported route (AOT-compile the pipeline with the `pytorch_wrapper` generator output and link that, not libHalide) is demonstrated by `apps/HelloPyTorch`. The reporter never followed up.

**Evidence:** Commit `14496928c` "Remove Introspection (#8273)" deleted `src/Introspection.cpp`; `grep -rn get_source_location src/` returns nothing. Working example: `apps/HelloPyTorch/README.md`, `apps/HelloPyTorch/setup.py`, `apps/HelloPyTorch/Makefile`.

The symbol in this report, `Halide::Internal::Introspection::get_source_location`, was removed entirely in #8273, so this exact link error can no longer occur. For the underlying question: don't link `libHalide` into the extension — AOT-compile the pipeline with a generator emitting `pytorch_wrapper` and link the generated static library, as demonstrated end-to-end in `apps/HelloPyTorch` (see its `README.md`, `Makefile`, and `setup.py`). Closing as a usage question; please open a Discussion if that path doesn't work.
