### ISSUE TITLE
fuzz-testing failure in fuzz_simplify

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7962]
Running fuzz_simplify with this input crashes:

[testcase-4633634714746880.zip](https://github.com/halide/Halide/files/13481998/testcase-4633634714746880.zip)

third_party/halide/halide/src/Simplify_Exprs.cpp:271:65: runtime error: signed integer overflow: 9223372036854775807 + 9223372036854775807 cannot be represented in type 'int64_t' (aka 'long')
    #0 0x555a645b8e82 in Halide::Internal::Simplify::visit(Halide::Internal::Ramp const*, Halide::Internal::Simplify::ExprInfo*) third_party/halide/halide/src/Simplify_Exprs.cpp:271:65
    #1 0x555a642f14a3 in Halide::Expr Halide::Internal::VariadicVisitor<Halide::Internal::Simplify, Halide::Expr, Halide::Internal::Stmt>::dispatch_expr<Halide::Internal::Simplify::ExprInfo*&>(Halide::Internal::BaseExprNode const*, Halide::Internal::Simplify::ExprInfo*&) third_party/halide/halide/src/IRVisitor.h:222:33
    #2 0x555a64b0481f in dispatch<Halide::Internal::Simplify::ExprInfo *&> third_party/halide/halide/src/IRVisitor.h:346:16
    #3 0x555a64b0481f in mutate third_party/halide/halide/src/Simplify_Internal.h:142:23
    #4 0x555a64b0481f in Halide::Internal::Simplify::visit(Halide::Internal::Mul const*, Halide::Internal::Simplify::ExprInfo*) third_party/halide/halide/src/Simplify_Mul.cpp:106:20
    #5 0x555a642f0cc7 in Halide::Expr Halide::Internal::VariadicVisitor<Halide::Internal::Simplify, Halide::Expr, Halide::Internal::Stmt>::dispatch_expr<Halide::Internal::Simplify::ExprInfo*&>(Halide::Internal::BaseExprNode const*, Halide::Internal::Simplify::ExprInfo*&) third_party/halide/halide/src/IRVisitor.h:192:33
    #6 0x555a64afe430 in dispatch<Halide::Internal::Simplify::ExprInfo *&> third_party/halide/halide/src/IRVisitor.h:346:16
    #7 0x555a64afe430 in mutate third_party/halide/halide/src/Simplify_Internal.h:142:23
    #8 0x555a64afe430 in Halide::Internal::Simplify::visit(Halide::Internal::Mul const*, Halide::Internal::Simplify::ExprInfo*) third_party/halide/halide/src/Simplify_Mul.cpp:8:14
    #9 0x555a642f0cc7 in Halide::Expr Halide::Internal::VariadicVisitor<Halide::Internal::Simplify, Halide::Expr, Halide::Internal::Stmt>::dispatch_expr<Halide::Internal::Simplify::ExprInfo*&>(Halide::Internal::BaseExprNode const*, Halide::Internal::Simplify::ExprInfo*&) third_party/halide/halide/src/IRVisitor.h:192:33
    #10 0x555a642ed7ed in dispatch<Halide::Internal::Simplify::ExprInfo *&> third_party/halide/halide/src/IRVisitor.h:346:16
    #11 0x555a642ed7ed in mutate third_party/halide/halide/src/Simplify_Internal.h:142:23
    #12 0x555a642ed7ed in Halide::Internal::simplify(Halide::Expr const&, bool, Halide::Internal::Scope<Halide::Internal::Interval> const&, Halide::Internal::Scope<Halide::Internal::ModulusRemainder> const&) third_party/halide/halide/src/Simplify.cpp:360:21
    #13 0x555a6329085c in test_expression third_party/halide/halide/test/fuzz/simplify.cpp:244:23
    #14 0x555a6329085c in LLVMFuzzerTestOneInput third_party/halide/halide/test/fuzz/simplify.cpp:359:5
    #15 0x555a6cd6c9b8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
    #16 0x555a6cd5e8ca in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:327:6
    #17 0x555a6cd6419f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:862:9
    #18 0x555a6cd5b392 in main third_party/llvm/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #19 0x7f7dd76db632 in __libc_start_main (/usr/grte/v5/lib64/libc.so.6+0x61632) (BuildId: 280088eab084c30a3992a9bce5c35b44)
    #20 0x555a631b6269 in _start /build/work/ab393f4ac612f9027aae6b1a7226027ba2a2/google3/blaze-out/k8-opt/bin/third_party/grte/v5_src/grte-scratch/BUILD/src/csu/../sysdeps/x86_64/start.S:120

SUMMARY: UndefinedBehaviorSanitizer: signed-integer-overflow third_party/halide/halide/src/Simplify_Exprs.cpp:271:65 in

**Comment by abadams** [comment]
Does not repro for me

**Comment by abadams** [comment]
> [!NOTE]
> **Automated triage:** this issue was flagged by Claude as likely safe to close, for the reason below. The reasoning was checked against the current source, and a second pass tried and failed to refute it, but no human verified this specific text. **If the reason is wrong, please reopen the issue and say so** — some fraction of these are expected to be wrong.

**Reason (CLOSE_FIXED):** The UBSAN report was signed-integer overflow in the `Ramp` visitor's bounds computation, which at the time did raw `int64_t` arithmetic: `bounds->min = std::min(base_bounds.min, base_bounds.min + (lanes - 1) * stride_bounds.min);`. That code is gone; the simplifier now computes ramp bounds through `ConstantInterval`, whose arithmetic is overflow-checked and saturating.

**Evidence:** Old code: `git show 5175d169c:src/Simplify_Exprs.cpp` line 271. Current code: `src/Simplify_Exprs.cpp:303` (`info->bounds = base_info.bounds + stride_info.bounds * ConstantInterval(0, lanes - 1);`), with `ConstantInterval::operator+` using `add_with_overflow` at `src/ConstantInterval.cpp:246-255`. Changed by 302aa1c35 ("Refactor ConstantInterval", #8179) and a9b8fbf7c ("Rework the simplifier to use ConstantInterval for bounds", #8222).

Closing: the overflowing raw `int64_t` bounds arithmetic in `Simplify::visit(const Ramp *)` was replaced by overflow-checked `ConstantInterval` arithmetic in #8179/#8222 (see `src/Simplify_Exprs.cpp:303` and `ConstantInterval::operator+` at `src/ConstantInterval.cpp:246`), so this UBSAN site no longer exists.
