### ISSUE TITLE
[upstream] `generator_aot_cleanup_on_error`/`generator_aotcpp_cleanup_on_error` don't work with RustiCL

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#8157]
This is most likely an upstream issue (will report there too), but documenting here just in case.
With `Halide_TARGET=host-opencl`:
```
$ OCL_ICD_VENDORS=libRusticlOpenCL.so RUSTICL_ENABLE=radeonsi gdb /repositories/halide/build-Clang17-release/test/generator/generator_aot_cleanup_on_error
GNU gdb (Debian 13.2-1+b1) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
No symbol table is loaded.  Use the "file" command.
Breakpoint 1 (__ubsan_handle_load_invalid_value) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 2 (__asan_report_error) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 3 (__ubsan::ScopedReport::~ScopedReport) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 4 (__ubsan::Diag::~Diag) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 5 (__sanitizer_print_stack_trace) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 6 (^abort) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 7 (SignalHandler) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 8 (llvm::sys::PrintStackTrace) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 9 (SignalHandler) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 10 (^raise) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 11 (llvm::sys::RunSignalHandlers) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 12 (^__assert_fail) pending.
Reading symbols from /repositories/halide/build-Clang17-release/test/generator/generator_aot_cleanup_on_error...
(gdb) r
Starting program: /repositories/halide/build-Clang17-release/test/generator/generator_aot_cleanup_on_error 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe62006c0 (LWP 171885)]
[New Thread 0x7fffe58006c0 (LWP 171886)]
[New Thread 0x7fffe4e006c0 (LWP 171887)]
[New Thread 0x7fffdfe006c0 (LWP 171888)]
[New Thread 0x7fffdf4006c0 (LWP 171889)]
[New Thread 0x7fffdea006c0 (LWP 171890)]
[New Thread 0x7fffde0006c0 (LWP 171891)]
[New Thread 0x7fffdd6006c0 (LWP 171892)]
[New Thread 0x7fffdcc006c0 (LWP 171893)]
[New Thread 0x7fffd3e006c0 (LWP 171894)]
Success!
[Thread 0x7fffd3e006c0 (LWP 171894) exited]
[Thread 0x7fffdd6006c0 (LWP 171892) exited]
[Thread 0x7fffde0006c0 (LWP 171891) exited]
[Thread 0x7fffdea006c0 (LWP 171890) exited]
[Thread 0x7fffdf4006c0 (LWP 171889) exited]
[Thread 0x7fffdfe006c0 (LWP 171888) exited]
[Thread 0x7fffe4e006c0 (LWP 171887) exited]
[Thread 0x7fffe58006c0 (LWP 171886) exited]
[Thread 0x7fffe62006c0 (LWP 171885) exited]
^C
Thread 1 "generator_aot_c" received signal SIGINT, Interrupt.
syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38      ../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff5a07d84 in std::sys::unix::futex::futex_wait (futex=0x555556c2ef44, expected=0, timeout=...) at library/std/src/sys/unix/futex.rs:62
#2  0x00007ffff5a104ca in std::sys::unix::locks::futex_condvar::Condvar::wait_optional_timeout (self=0x555556c2ef44, mutex=0x555556c2ee98, timeout=...) at library/std/src/sys/unix/locks/futex_condvar.rs:49
#3  std::sys::unix::locks::futex_condvar::Condvar::wait_timeout (self=0x555556c2ef44, mutex=0x555556c2ee98, timeout=...) at library/std/src/sys/unix/locks/futex_condvar.rs:37
#4  0x00007ffff592f34b in std::sync::condvar::Condvar::wait_timeout::hfdfba8c68f3119f3 () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#5  0x00007ffff59a36fe in rusticl::core::event::Event::wait::heaba24469866f284 () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#6  0x00007ffff5997f60 in rusticl::core::queue::Queue::flush::{{closure}}::hbe0aad4f2e3dd3ca () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#7  0x00007ffff59900bb in core::option::Option<T>::map::h86b33bc6be96bf17 () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#8  0x00007ffff5997e24 in rusticl::core::queue::Queue::flush::hca8c48c255e448f6 () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#9  0x00007ffff58f5b20 in rusticl::api::queue::finish::ha63dc1ef3200d121 () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#10 0x00007ffff58f5aa9 in rusticl::api::queue::cl_finish::hb065083afbabf5de () from /lib/x86_64-linux-gnu/libRusticlOpenCL.so
#11 0x0000555555569c23 in halide_opencl_device_release ()
#12 0x00007ffff7fcc0ca in _dl_call_fini (closure_map=closure_map@entry=0x7ffff7ffe2c0) at ./elf/dl-call_fini.c:43
#13 0x00007ffff7fcfc8e in _dl_fini () at ./elf/dl-fini.c:114
#14 0x00007ffff7a5c955 in __run_exit_handlers (status=0, listp=0x7ffff7bf1840 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:111
#15 0x00007ffff7a5ca8a in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:141
#16 0x00007ffff7a456d1 in __libc_start_call_main (main=main@entry=0x55555555c8e0 <main(int, char**)>, argc=argc@entry=1, argv=argv@entry=0x7fffffffda68) at ../sysdeps/nptl/libc_start_call_main.h:74
#17 0x00007ffff7a45785 in __libc_start_main_impl (main=0x55555555c8e0 <main(int, char**)>, argc=1, argv=0x7fffffffda68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda58) at ../csu/libc-start.c:360
#18 0x000055555555c681 in _start ()
```
These are the only two tests that appear to fail

**Comment by LebedevRI** [comment]
Hm, weirdly-enough, does not appear to happen with halide built with llvm18.
